<a href="https://colab.research.google.com/github/jaityagi63/TDS/blob/master/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

so in simple linear regression we try to find relation between input and ouput column

but in multiple linear regression we try to find relation between multiple input column and a single output column



In [1]:
#generating the data
import numpy as np
import pandas as pd
import plotly.graph_objects as go

# Generate CGPA between 5.0 and 10.0
cgpa = np.round(np.random.uniform(5.0, 10.0, 100), 2)

# Generate IQ between 80 and 160
iq = np.random.randint(80, 161, 100)

# Generate placement salary in LPA with some relationship:
# Assume placement depends positively on CGPA and IQ plus some noise
placement = 0.5 * cgpa + 0.03 * iq + np.random.normal(0, 0.5, 100)
placement = np.round(placement, 2)

# Create DataFrame
df = pd.DataFrame({
    'CGPA': cgpa,
    'IQ': iq,
    'Placement_LPA': placement
})

print(df.head())


   CGPA   IQ  Placement_LPA
0  9.20   83           7.39
1  6.13  134           6.58
2  9.68   84           7.22
3  7.68  124           7.68
4  5.09   85           4.95


In simple linear regression, we get a line:

$$
y = mx + b
$$

But in multiple linear regression, we get a plane (or a hyperplane in higher dimensions) that looks like this:

$$
y = w_1 x_1 + w_2 x_2 + \cdots + w_n x_n + b
$$


goal is to find
$$
 w1,w2,w3...,w4,b
$$




In [2]:
x = df[['CGPA','IQ']]
y = df['Placement_LPA']


In [3]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score


In [6]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression


# Train linear model
X = df[['CGPA', 'IQ']]
y = df['Placement_LPA']
model = LinearRegression().fit(X, y)

# Create a grid of CGPA and IQ values
cgpa_range = np.linspace(df['CGPA'].min(), df['CGPA'].max(), 30)
iq_range = np.linspace(df['IQ'].min(), df['IQ'].max(), 30)
cgpa_grid, iq_grid = np.meshgrid(cgpa_range, iq_range)
X_grid = np.column_stack([cgpa_grid.ravel(), iq_grid.ravel()])

# Predict Placement_LPA over the grid
placement_pred = model.predict(X_grid).reshape(cgpa_grid.shape)

# 3D scatter plot of original data
fig = px.scatter_3d(df, x='CGPA', y='IQ', z='Placement_LPA', title='3D Scatter Plot')

# Add regression surface
fig.add_trace(
    go.Surface(x=cgpa_range, y=iq_range, z=placement_pred, name='Regression Plane', opacity=0.5)
)

fig.show()


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [7]:
#creating my own class to dot this
import numpy as np
from sklearn.datasets import load_diabetes
import pandas as pd

In [8]:
X,Y = load_diabetes(return_X_y=True)

(442, 10)

In [13]:
Y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [15]:
from sklearn.linear_model import LinearRegression
meraLR = LinearRegression()
meraLR.fit(X_train,Y_train)

LinearRegression()

In [17]:
print(meraLR.predict(X_test))
print(Y_test)

[154.1213881  204.81835118 124.93755353 106.08950893 258.5348576
 256.3310074  118.75087616 119.52440696 101.50816735 190.54048661
 141.70656811 172.51883961 174.33861649 134.80942706 294.13994537
  94.11798038 211.97059795 156.49579378 134.21000428 119.62664644
 148.87842251 165.00873409 151.10021038 176.04063756 133.27769647
 221.29555392 197.17324941  96.1577688   50.26012711 230.48580317
 242.06073866 114.11129218  67.07532417  94.52943825 201.21415375
 167.05136201 159.881268   192.78746659 114.49551325 233.48234551
 140.82563045 121.0680409  192.27480772 191.12738845 179.16865788
 148.34935601 163.47414622 276.81647884 100.17926432 164.10555298
 255.80762189 136.9466204  152.37503699 107.92237882 194.21924678
  77.34670792 118.50482479  68.38335763 154.29258529 162.48840259
 168.36788326 156.87790322  97.14191797 238.1671215  145.46179904
 117.65702433 168.88784311 198.38683887 118.24053714 124.64552812
 223.17700368 200.63012386 129.54414666 158.1584765  154.332565
 114.47070769

In [18]:
from sklearn.metrics import r2_score
r2_score(Y_test,meraLR.predict(X_test))

0.4399338661568968

In [24]:
meraLR.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

for multiple linear regression we use this odinary least square
### 📐 Normal Equation for Multiple Linear Regression

The closed-form solution for the optimal weights \( \boldsymbol{\beta} \) is:

$$
\boldsymbol{\beta} = (X^T X)^{-1} X^T y
$$

Where:

- \( X \) is the **design matrix** (with shape \( m \times n \))  
- \( y \) is the **target vector** (with shape \( m \times 1 \))  
- \( X^T \) is the **transpose** of \( X \)  
- \( (X^T X)^{-1} \) is the **inverse** of \( X^T X \)  
- \( \boldsymbol{\beta} \) is the **vector of learned coefficients**



In [32]:
class meraLR:
  def __init__(self):
    self.coeff_ = None
    self.intercept_ = None
  def fit(self,X_train,Y_train):
    X_train = np.insert(X_train,0,1,axis=1)

    betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(Y_train)
    self.intercept_ = betas[0]
    self.coeff_ = betas[1:]

  def predict(self,X_test):
    y_pred = np.dot(X_test,self.coeff_) + self.intercept_
    return y_pred

In [35]:
new = meraLR()
new.fit(X_train,Y_train)
new_predict = new.predict(X_test)
new_predict



array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

problem with OLS or closed from is that taking a inverse is very expansive computation wise we talking about in term of $$R^3$$which is very exapansive the fastest of the algo to compute inverse is in term of $$R^2$$ so we use gradient descent which is fairly fast compare to OLS